"""
"""
import pytest
from src.bots.move_dots import move_dots_after_refs


@pytest.mark.skip
def test_part3():
    input_text = """Խորհուրդ է տրվում լյարդի ճարպային հիվանդություն ունեցող մարդկանց չօգտագործել ալկոհոլ<ref name="Ant2019" /><ref name="Sin2017" />։ ՈԱՖԼՀ-ի բուժումը սովորաբար այլ կերպ է իրականացվում՝ սննդակարգի փոփոխություններով և [[Քաշի կորուստ|քաշի կորստի]] նպատակով վարժություններով <ref name="NIH2016" /> : Ծանր հիվանդների մոտ լյարդի փոխպատվաստումը կարող է լինել տարբերակ<ref name="NIH2016" />։ Բոլոր չափից շատ խմողների ավելի քան 90%-ը զարգացնում է լյարդի ճարպային հիվանդություն, մինչդեռ մոտ 25%-ը զարգացնում է ավելի ծանր ալկոհոլային հեպատիտ <ref name="Bas2011">{{Cite journal|last=Basra|first=Sarpreet|title=Definition, epidemiology and magnitude of alcoholic hepatitis|journal=World Journal of Hepatology|date=2011|volume=3|issue=5|pages=108–113|doi=10.4254/wjh.v3.i5.108|pmid=21731902|pmc=3124876}}</ref>։ Ոչ ալկոհոլային ճարպաթթուների լյարդային հիվանդությունը (ՈԱԼՀ) ազդում է արևմտյան երկրների բնակչության մոտ 30%-ի և Ասիայի բնակչության 10%-ի վրա<ref name="Sin2017" />։ ԱՄՆ-ում ոչ ալկոհոլային ճարպաթթուների (ՈԱՃՀ) համախտանիշը (ՈԱՃՀ) ազդում է երեխաների մոտ 10%-ի վրա <ref name="NIH2016" /> : Այն ավելի հաճախ է հանդիպում տարեց մարդկանց և տղամարդկանց մոտ<ref name="AFP2013" /><ref name="Ant2019" />։"""
    expected = """Խորհուրդ է տրվում լյարդի ճարպային հիվանդություն ունեցող մարդկանց չօգտագործել ալկոհոլ<ref name="Ant2019" /><ref name="Sin2017" />։ ՈԱՖԼՀ-ի բուժումը սովորաբար այլ կերպ է իրականացվում՝ սննդակարգի փոփոխություններով և [[Քաշի կորուստ|քաշի կորստի]] նպատակով վարժություններով <ref name="NIH2016" />: Ծանր հիվանդների մոտ լյարդի փոխպատվաստումը կարող է լինել տարբերակ<ref name="NIH2016" />։ Բոլոր չափից շատ խմողների ավելի քան 90%-ը զարգացնում է լյարդի ճարպային հիվանդություն, մինչդեռ մոտ 25%-ը զարգացնում է ավելի ծանր ալկոհոլային հեպատիտ <ref name="Bas2011">{{Cite journal|last=Basra|first=Sarpreet|title=Definition, epidemiology and magnitude of alcoholic hepatitis|journal=World Journal of Hepatology|date=2011|volume=3|issue=5|pages=108–113|doi=10.4254/wjh.v3.i5.108|pmid=21731902|pmc=3124876}}</ref>։ Ոչ ալկոհոլային ճարպաթթուների լյարդային հիվանդությունը (ՈԱԼՀ) ազդում է արևմտյան երկրների բնակչության մոտ 30%-ի և Ասիայի բնակչության 10%-ի վրա<ref name="Sin2017" />։ ԱՄՆ-ում ոչ ալկոհոլային ճարպաթթուների (ՈԱՃՀ) համախտանիշը (ՈԱՃՀ) ազդում է երեխաների մոտ 10%-ի վրա <ref name="NIH2016" />: Այն ավելի հաճախ է հանդիպում տարեց մարդկանց և տղամարդկանց մոտ<ref name="AFP2013" /><ref name="Ant2019" />։"""
    assert move_dots_after_refs(input_text, 'hy') == expected


@pytest.mark.skip
def test_part4():
    input_text = """Գոյություն ունի լյարդի ճարպային հիվանդության երկու տեսակ՝ ոչ ալկոհոլային ճարպային լյարդի հիվանդություն (ՈԱՃՀ) և ալկոհոլային լյարդի հիվանդություն <ref name="NIH2016" />։ ՈԱՃՀՀ-ն բաղկացած է պարզ ճարպային լյարդից և ոչ ալկոհոլային ստեատոհեպատիտից (ՈԱՃՀ): <ref name="AFP2013">{{Cite journal|last=Iser|first=D|last2=Ryan|first2=M|title=Fatty liver disease—a practical guide for GPs.|journal=Australian Family Physician|date=July 2013|volume=42|issue=7|pages=444–7|pmid=23826593}}</ref><ref name="NIH2016" /> Հիմնական ռիսկերից են [[Էթիլ սպիրտ|ալկոհոլը]], [[Տիպ 2 շաքարային դիաբետ|2-րդ տիպի շաքարախտը]] և [[Ճարպակալում|ճարպակալումը]] <ref name="Ant2019" /><ref name="NIH2016" />։ Այլ ռիսկի գործոններից են որոշակի դեղամիջոցները, ինչպիսիք են [[Գլյուկոկորտիկոիդներ|գլյուկոկորտիկոիդները]] և [[Հեպատիտ C|հեպատիտ C-ն]] : <ref name="NIH2016" /> Անհասկանալի է, թե ինչու են ոչ ալկոհոլային ճարպային լյարդի հիվանդություն ունեցող որոշ մարդիկ զարգացնում պարզ ճարպային լյարդ, իսկ մյուսները՝ ոչ ալկոհոլային հեպատիտ: <ref name="NIH2016" /> Ախտորոշումը հիմնված է [[Անամնեզ|բժշկական պատմության]] վրա, որը հաստատվում է արյան անալիզներով, բժշկական պատկերագրական հետազոտություններով և երբեմն լյարդի բիոպսիայով <ref name="NIH2016" />։"""
    expected = """Գոյություն ունի լյարդի ճարպային հիվանդության երկու տեսակ՝ ոչ ալկոհոլային ճարպային լյարդի հիվանդություն (ՈԱՃՀ) և ալկոհոլային լյարդի հիվանդություն <ref name="NIH2016" />։ ՈԱՃՀՀ-ն բաղկացած է պարզ ճարպային լյարդից և ոչ ալկոհոլային ստեատոհեպատիտից (ՈԱՃՀ)<ref name="AFP2013">{{Cite journal|last=Iser|first=D|last2=Ryan|first2=M|title=Fatty liver disease—a practical guide for GPs.|journal=Australian Family Physician|date=July 2013|volume=42|issue=7|pages=444–7|pmid=23826593}}</ref><ref name="NIH2016" />: Հիմնական ռիսկերից են [[Էթիլ սպիրտ|ալկոհոլը]], [[Տիպ 2 շաքարային դիաբետ|2-րդ տիպի շաքարախտը]] և [[Ճարպակալում|ճարպակալումը]] <ref name="Ant2019" /><ref name="NIH2016" />։ Այլ ռիսկի գործոններից են որոշակի դեղամիջոցները, ինչպիսիք են [[Գլյուկոկորտիկոիդներ|գլյուկոկորտիկոիդները]] և [[Հեպատիտ C|հեպատիտ C-ն]] <ref name="NIH2016" />: Անհասկանալի է, թե ինչու են ոչ ալկոհոլային ճարպային լյարդի հիվանդություն ունեցող որոշ մարդիկ զարգացնում պարզ ճարպային լյարդ, իսկ մյուսները՝ ոչ ալկոհոլային հեպատիտ<ref name="NIH2016" />: Ախտորոշումը հիմնված է [[Անամնեզ|բժշկական պատմության]] վրա, որը հաստատվում է արյան անալիզներով, բժշկական պատկերագրական հետազոտություններով և երբեմն լյարդի բիոպսիայով<ref name="NIH2016" />։"""
    assert move_dots_after_refs(input_text, 'hy') == expected


def test_part5():
    input_text = """text part 1 <ref name="NIH2016" />։ text part 2: <ref name="AFP2013">{{Cite journal|last=Iser|first=D|last2=Ryan|first2=M|title=Fatty liver disease—a practical guide for GPs.|journal=Australian Family Physician|date=July 2013|volume=42|issue=7|pages=444–7|pmid=23826593}}</ref><ref name="NIH2016" /> some text [[links|label]] other [[text]] <small>text</small> <ref name="Ant2019" /><ref name="NIH2016" />։ hello!! [[2020|hi]] և [[Հեպատիտ C|հեպատիտ C-ն]] : <ref name="NIH2016" /> random texts: <ref name="NIH2016" /> last part <ref name="NIH2016" />։"""
    expected = """text part 1 <ref name="NIH2016" />։ text part 2<ref name="AFP2013">{{Cite journal|last=Iser|first=D|last2=Ryan|first2=M|title=Fatty liver disease—a practical guide for GPs.|journal=Australian Family Physician|date=July 2013|volume=42|issue=7|pages=444–7|pmid=23826593}}</ref><ref name="NIH2016" />: some text [[links|label]] other [[text]] <small>text</small> <ref name="Ant2019" /><ref name="NIH2016" />։ hello!! [[2020|hi]] և [[Հեպատիտ C|հեպատիտ C-ն]] <ref name="NIH2016" />: random texts<ref name="NIH2016" />: last part <ref name="NIH2016" />։"""
    assert move_dots_after_refs(input_text, 'hy') == expected
